<main>
<div class="media-socials-container">
    <?php
    $socials = [
        // Najbardziej znane platformy społecznościowe
        ['name' => 'Facebook', 'url' => 'https://facebook.com', 'icon' => '📘'],
        ['name' => 'Instagram', 'url' => 'https://instagram.com', 'icon' => '📸'],
        ['name' => 'Snapchat', 'url' => 'https://snapchat.com', 'icon' => '👻'],
        ['name' => 'Pinterest', 'url' => 'https://pinterest.com', 'icon' => '📌'],
        ['name' => 'Google', 'url' => 'https://google.com', 'icon' => '🔎'],
        ['name' => 'Google Maps', 'url' => 'https://maps.google.com', 'icon' => '🗺️'],
        ['name' => 'Google Drive', 'url' => 'https://drive.google.com', 'icon' => '☁️'],
        ['name' => 'Google Photos', 'url' => 'https://photos.google.com', 'icon' => '🖼️'],
        ['name' => 'Google Meet', 'url' => 'https://meet.google.com', 'icon' => '🎥'],
        ['name' => 'YouTube', 'url' => 'https://youtube.com', 'icon' => '▶️'],
        ['name' => 'GitHub', 'url' => 'https://github.com', 'icon' => '🐙'],
        ['name' => 'Bing', 'url' => 'https://bing.com', 'icon' => '🅱️'],
        ['name' => 'Twitter', 'url' => 'https://twitter.com', 'icon' => '🐦'],
        ['name' => 'X', 'url' => 'https://x.com', 'icon' => '❌'],
        ['name' => 'TikTok', 'url' => 'https://tiktok.com', 'icon' => '🎵'],
        ['name' => 'Reddit', 'url' => 'https://reddit.com', 'icon' => '👽'],
        ['name' => 'Telegram', 'url' => 'https://telegram.org', 'icon' => '✈️'],
        ['name' => 'Discord', 'url' => 'https://discord.com', 'icon' => '🎮'],
        ['name' => 'Twitch', 'url' => 'https://twitch.tv', 'icon' => '🟣'],
        ['name' => 'Skype', 'url' => 'https://skype.com', 'icon' => '📞'],
        ['name' => 'Messenger', 'url' => 'https://messenger.com', 'icon' => '💭'],
        ['name' => 'WhatsApp', 'url' => 'https://whatsapp.com', 'icon' => '💬'],
        ['name' => 'LinkedIn', 'url' => 'https://linkedin.com', 'icon' => '💼'],
        ['name' => 'Spotify', 'url' => 'https://spotify.com', 'icon' => '🎵'],
        ['name' => 'Apple Music', 'url' => 'https://music.apple.com', 'icon' => '🍏'],
        ['name' => 'SoundCloud', 'url' => 'https://soundcloud.com', 'icon' => '🎧'],
        ['name' => 'Songsterr', 'url' => 'https://songsterr.com', 'icon' => '🎸'],
        ['name' => 'Vimeo', 'url' => 'https://vimeo.com', 'icon' => '🎬'],
        ['name' => 'Tumblr', 'url' => 'https://tumblr.com', 'icon' => '🌀'],
        ['name' => 'Flickr', 'url' => 'https://flickr.com', 'icon' => '📷'],
        ['name' => 'Reddit', 'url' => 'https://reddit.com', 'icon' => '👽'],
        ['name' => 'Quora', 'url' => 'https://quora.com', 'icon' => '❓'],
        ['name' => 'Medium', 'url' => 'https://medium.com', 'icon' => '✍️'],
        ['name' => 'Dribbble', 'url' => 'https://dribbble.com', 'icon' => '🏀'],
        ['name' => 'Behance', 'url' => 'https://behance.net', 'icon' => '🎨'],
        ['name' => 'Slack', 'url' => 'https://slack.com', 'icon' => '💬'],
        ['name' => 'Telegram', 'url' => 'https://telegram.org', 'icon' => '✈️'],
        ['name' => 'WeChat', 'url' => 'https://wechat.com', 'icon' => '💭'],
        ['name' => 'VK', 'url' => 'https://vk.com', 'icon' => '🌐'],
        ['name' => 'Line', 'url' => 'https://line.me', 'icon' => '🟩'],
        ['name' => 'Viber', 'url' => 'https://viber.com', 'icon' => '📱'],
        ['name' => 'KakaoTalk', 'url' => 'https://kakaocorp.com', 'icon' => '🟨'],
        ['name' => 'QQ', 'url' => 'https://qq.com', 'icon' => '🐧'],
        ['name' => 'Sina Weibo', 'url' => 'https://weibo.com', 'icon' => '📰'],
        ['name' => 'Blogger', 'url' => 'https://blogger.com', 'icon' => '📝'],
        ['name' => 'WordPress', 'url' => 'https://wordpress.com', 'icon' => '🌐'],
        ['name' => 'Patreon', 'url' => 'https://patreon.com', 'icon' => '💰'],
        ['name' => 'OnlyFans', 'url' => 'https://onlyfans.com', 'icon' => '🔞'],
        ['name' => 'Mastodon', 'url' => 'https://mastodon.social', 'icon' => '🐘'],
        ['name' => 'Tinder', 'url' => 'https://tinder.com', 'icon' => '🔥'],
        ['name' => 'Badoo', 'url' => 'https://badoo.com', 'icon' => '💘'],
        ['name' => 'Meetup', 'url' => 'https://meetup.com', 'icon' => '🤝'],
        ['name' => 'Myspace', 'url' => 'https://myspace.com', 'icon' => '🎤'],
        ['name' => 'Goodreads', 'url' => 'https://goodreads.com', 'icon' => '📚'],
        ['name' => 'Steam', 'url' => 'https://store.steampowered.com', 'icon' => '🎮'],
        ['name' => 'Epic Games', 'url' => 'https://epicgames.com', 'icon' => '🕹️'],
        ['name' => 'Origin', 'url' => 'https://origin.com', 'icon' => '🟠'],
        ['name' => 'Battle.net', 'url' => 'https://battle.net', 'icon' => '⚔️'],
        ['name' => 'PlayStation Network', 'url' => 'https://playstation.com', 'icon' => '🎮'],
        ['name' => 'Xbox', 'url' => 'https://xbox.com', 'icon' => '🟩'],
        ['name' => 'Nintendo', 'url' => 'https://nintendo.com', 'icon' => '🎮'],
        ['name' => 'Trello', 'url' => 'https://trello.com', 'icon' => '📋'],
        ['name' => 'Asana', 'url' => 'https://asana.com', 'icon' => '✅'],
        ['name' => 'Notion', 'url' => 'https://notion.so', 'icon' => '🗒️'],
        ['name' => 'Dropbox', 'url' => 'https://dropbox.com', 'icon' => '📦'],
        ['name' => 'Zoom', 'url' => 'https://zoom.us', 'icon' => '🎦'],
        ['name' => 'Teams', 'url' => 'https://teams.microsoft.com', 'icon' => '👥'],
        ['name' => 'Outlook', 'url' => 'https://outlook.com', 'icon' => '📧'],
        ['name' => 'Yahoo', 'url' => 'https://yahoo.com', 'icon' => '🟪'],
        ['name' => 'Amazon', 'url' => 'https://amazon.com', 'icon' => '🛒'],
        ['name' => 'Allegro', 'url' => 'https://allegro.pl', 'icon' => '🛍️'],
        ['name' => 'eBay', 'url' => 'https://ebay.com', 'icon' => '💸'],
        ['name' => 'OLX', 'url' => 'https://olx.pl', 'icon' => '📦'],
        ['name' => 'PayPal', 'url' => 'https://paypal.com', 'icon' => '💳'],
        ['name' => 'AliExpress', 'url' => 'https://aliexpress.com', 'icon' => '📦'],
        ['name' => 'Booking', 'url' => 'https://booking.com', 'icon' => '🏨'],
        ['name' => 'Airbnb', 'url' => 'https://airbnb.com', 'icon' => '🏠'],
        ['name' => 'Uber', 'url' => 'https://uber.com', 'icon' => '🚗'],
        ['name' => 'Bolt', 'url' => 'https://bolt.eu', 'icon' => '⚡'],
        ['name' => 'Glovo', 'url' => 'https://glovoapp.com', 'icon' => '🛵'],
        ['name' => 'Pyszne', 'url' => 'https://pyszne.pl', 'icon' => '🍔'],
        ['name' => 'Just Eat', 'url' => 'https://just-eat.com', 'icon' => '🍕'],
        ['name' => 'Netflix', 'url' => 'https://netflix.com', 'icon' => '🎬'],
        ['name' => 'HBO Max', 'url' => 'https://hbomax.com', 'icon' => '📺'],
        ['name' => 'Disney+', 'url' => 'https://disneyplus.com', 'icon' => '🧞'],
        ['name' => 'Prime Video', 'url' => 'https://primevideo.com', 'icon' => '🎥'],
        ['name' => 'Player', 'url' => 'https://player.pl', 'icon' => '📺'],
        ['name' => 'Canal+', 'url' => 'https://canalplus.com', 'icon' => '➕'],
        ['name' => 'Humble Bundle', 'url' => 'https://humblebundle.com', 'icon' => '🎁'],
        ['name' => 'GOG', 'url' => 'https://gog.com', 'icon' => '🕹️'],
        ['name' => 'Deezer', 'url' => 'https://deezer.com', 'icon' => '🎶'],
        ['name' => 'Shazam', 'url' => 'https://shazam.com', 'icon' => '🔎'],
        ['name' => 'Last.fm', 'url' => 'https://last.fm', 'icon' => '📻'],
        ['name' => 'Bandcamp', 'url' => 'https://bandcamp.com', 'icon' => '🎶'],
        ['name' => 'ReverbNation', 'url' => 'https://reverbnation.com', 'icon' => '🎸'],
        ['name' => 'Smule', 'url' => 'https://smule.com', 'icon' => '🎤'],
        ['name' => 'Houseparty', 'url' => 'https://houseparty.com', 'icon' => '🏠'],
        ['name' => 'Peach', 'url' => 'https://peach.cool', 'icon' => '🍑'],
        ['name' => 'Byte', 'url' => 'https://byte.co', 'icon' => '🟠'],
        ['name' => 'Caffeine', 'url' => 'https://caffeine.tv', 'icon' => '☕'],
        ['name' => 'Yubo', 'url' => 'https://yubo.live', 'icon' => '🟡'],
        ['name' => 'Amino', 'url' => 'https://aminoapps.com', 'icon' => '🧬'],
        ['name' => 'Minds', 'url' => 'https://minds.com', 'icon' => '🧠'],
        ['name' => 'CloutHub', 'url' => 'https://clouthub.com', 'icon' => '💬'],
        ['name' => 'BitChute', 'url' => 'https://bitchute.com', 'icon' => '📺'],
        ['name' => 'DLive', 'url' => 'https://dlive.tv', 'icon' => '🟡'],
        ['name' => 'PeerTube', 'url' => 'https://joinpeertube.org', 'icon' => '🔗'],
        ['name' => 'Odysee', 'url' => 'https://odysee.com', 'icon' => '🌊'],
        ['name' => 'Rizzle', 'url' => 'https://rizzle.tv', 'icon' => '🎥'],
        ['name' => 'Unfold', 'url' => 'https://unfold.com', 'icon' => '📖'],
        ['name' => 'Swarm', 'url' => 'https://swarmapp.com', 'icon' => '🐝'],
        ['name' => 'VK Music', 'url' => 'https://vk.com/music', 'icon' => '🎵'],
        ['name' => 'VK Video', 'url' => 'https://vk.com/video', 'icon' => '🎬'],
        ['name' => 'VK Live', 'url' => 'https://vk.com/live', 'icon' => '🔴'],
        ['name' => 'VK Games', 'url' => 'https://vk.com/games', 'icon' => '🎮'],
        ['name' => 'VK Clips', 'url' => 'https://vk.com/clips', 'icon' => '🎞️'],
        ['name' => 'VK Calls', 'url' => 'https://vk.com/calls', 'icon' => '📞'],
        ['name' => 'VK Messenger', 'url' => 'https://vk.com/messenger', 'icon' => '💬'],
        ['name' => 'VK Pay', 'url' => 'https://vk.com/pay', 'icon' => '💳'],
        ['name' => 'VK Mini Apps', 'url' => 'https://vk.com/miniapps', 'icon' => '📱'],
    ];

    foreach ($socials as $social) {
        echo '<a class="media-social-link" href="' . htmlspecialchars($social['url']) . '" target="_blank">
            <div class="media-social-card">
                <span class="media-social-icon">' . $social['icon'] . '</span>
                <span class="media-social-name">' . htmlspecialchars($social['name']) . '</span>
            </div>
        </a>';
    }
    ?>
</div>
</main>